[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
altcoin = "38m5iMhNn13EfKF1uUqX2HLAGgqpmiNDxtSJSJsJKhaD"


[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "devnet"
cluster = "LocalNet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test]
startup_wait = 100000
shutdown_wait = 100000

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
